# $Id: GNUmakefile 66370 2012-12-18 09:25:03Z gcosmo $
# --------------------------------------------------------------
# GNUmakefile for tests module.  Gabriele Cosmo, 27/06/98.
# --------------------------------------------------------------

name := test02
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../..
endif

.PHONY: all
 
all: lib bin

include $(G4INSTALL)/config/binmake.gmk

