all:
	rm -f energy_efficiency_scy_computing.bbl
	pdflatex  energy_efficiency_scy_computing.tex
	bibtex energy_efficiency_scy_computing
	pdflatex energy_efficiency_scy_computing.tex
	pdflatex energy_efficiency_scy_computing.tex

clean:
	rm -f energy_efficiency_scy_computing.aux
	rm -f energy_efficiency_scy_computing.bbl
	rm -f energy_efficiency_scy_computing.blg
	rm -f energy_efficiency_scy_computing.log
	rm -f energy_efficiency_scy_computing.out
	rm -f energy_efficiency_scy_computing.toc
	rm -f energy_efficiency_scy_computing.lof
	rm -f energy_efficiency_scy_computing.lot




