# $Id: GNUmakefile 66371 2012-12-18 09:26:26Z gcosmo $
# --------------------------------------------------------------

ifndef G4TARGET
  G4TARGET := harp_reader
endif

name := ${G4TARGET}

G4EXEC_BUILD  = true

include $(G4INSTALL)/config/architecture.gmk

include $(G4INSTALL)/config/binmake.gmk

