# $Id: run2.mac 66356 2012-12-18 09:02:32Z gcosmo $
#
#

/run/initialize

/mydet/SelectDetector Torus
#/mydet/SelectDetector Box
#/mydet/SelectDetector Sphere
#/mydet/SelectDetector Tube
#/mydet/SelectDetector Orb
#/mydet/SelectDetector Cone
#/mydet/SelectDetector TwistedTubs 
#/mydet/SelectDetector  TwistedBox
#/mydet/SelectDetector TwistedTrd
#/mydet/SelectDetector  TwistedTrap
#/mydet/SelectDetector TwistedTrap2
#/mydet/SelectDetector TwistedTrap3


/run/beamOn 10
