# $Id: GNUmakefile 66366 2012-12-18 09:16:47Z gcosmo $
# --------------------------------------------------------------
# GNUmakefile for tests module.  Gabriele Cosmo, 27/06/98.
# --------------------------------------------------------------

name := test16
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  G4INSTALL = ../..
endif

.PHONY: all
 
all: lib bin

include $(G4INSTALL)/config/binmake.gmk

