# $Id: storeTables.mac 66892 2013-01-17 10:57:59Z gunter $
#
# Macro file for "testEm3.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
#
/testem/phys/addPhysics  emstandard
#/testem/phys/addPhysics  standardLPM
#
/run/initialize
/process/eLoss/verbose 1
/process/eLoss/CSDARange true
/run/beamOn 3
#
/run/particle/storePhysicsTable physdata
#
/gun/particle e-
/gun/energy 1 GeV
#
#/run/beamOn 3	
#
/run/particle/retrievePhysicsTable physdata
#
/random/resetEngineFrom currentRun.rndm
/run/beamOn 3
#
